IF EXISTS ( SELECT * 
            FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[usp_UpdateTarjetasData]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE [dbo].[usp_UpdateTarjetasData]
END
GO
CREATE PROCEDURE dbo.usp_UpdateTarjetasData(
 
) AS 
BEGIN
	UPDATE TARJETAS 
	SET NUMEROTARJETA=@NUMEROTARJETA, CCV=@CCV, SALDO=@SALDO, DISPONIBLE=@DISPONIBLE
	WHERE ID=@ID
END
GO

IF EXISTS (
    SELECT *
    FROM sysobjects
    WHERE id = object_id(N'[dbo].[usp_AddTarjetasData]')
        AND OBJECTPROPERTY(id, N'IsProcedure') = 1
)
BEGIN
    DROP PROCEDURE [dbo].[usp_usp_AddTarjetasData]
END
GO
CREATE PROCEDURE dbo.usp_usp_AddTarjetasData (
    @NUMEROTARJETA INT,
    @CCV INT,
	@SALDO INT,
	@DISPONIBLE INT,
    @ID INT OUTPUT
) AS
BEGIN
    INSERT INTO TARJETAS(NUMEROTARJETA, CCV, SALDO, DISPONIBLE)
    VALUES (@NUMEROTARJETA, @CCV, @SALDO, @DISPONIBLE)

    SET @ID = SCOPE_IDENTITY()
END
GO


SELECT * FROM USUARIO

IF OBJECT_ID('dbo.TARJETAS', 'U') IS NOT NULL 
  DROP TABLE dbo.TARJETAS 
GO
CREATE TABLE TARJETAS
( 
    ID         INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NUMEROTARJETA		INT,
	CCV			INT,
	SALDO INT,
	DISPONIBLE INT
)


IF EXISTS ( SELECT * 
            FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[usp_QueryTarjetasData]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE [dbo].[usp_QueryTarjetasData]
END
GO
CREATE PROCEDURE dbo.usp_QueryTarjetasData AS 
BEGIN
	SELECT * FROM TARJETAS 
END
GO

IF EXISTS ( SELECT * 
            FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[usp_DeleteTarjetasData]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE [dbo].[usp_DeleteTarjetasData]
END
GO
CREATE PROCEDURE dbo.usp_DeleteTarjetasData(
    @ID         INT
) AS 
BEGIN
	DELETE FROM TARJETAS 
	WHERE ID=@ID
END
GO

INSERT INTO TARJETAS (NUMEROTARJETA, CCV, SALDO, DISPONIBLE) 
VALUES 
    (789,226, 500, 1);
SELECT * FROM TARJETAS



IF OBJECT_ID('dbo.USUARIO', 'U') IS NOT NULL 
  DROP TABLE dbo.USUARIO 
GO
CREATE TABLE USUARIO
( 
    ID         INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	NOMBRE	VARCHAR(200) NOT NULL, 
	CONTRASENA	VARCHAR(200) NOT NULL, 
	EMAIL		VARCHAR(200) NOT NULL, 
	TIPOMEMBRESIA	    VARCHAR(200) NOT NULL,
	FECHAINICIO      VARCHAR(200) NOT NULL, 
    FECHAFINALIZACION      VARCHAR(200) NOT NULL,
	UNIDADTEMP			VARCHAR(200) NOT NULL,
	FORMATOHORAS			VARCHAR(200) NOT NULL,
	FORMATOFECHAS			VARCHAR(200) NOT NULL,
    PUNTOSTOTALES	    INT,
    PUNTOSDIARIOS	    INT,
	FECHAACTUALIZACION		VARCHAR(200) NOT NULL, 
	IDTARJETA INT
	)

IF EXISTS (
    SELECT *
    FROM sysobjects
    WHERE id = object_id(N'[dbo].[usp_AddUserData]')
        AND OBJECTPROPERTY(id, N'IsProcedure') = 1
)
BEGIN
    DROP PROCEDURE [dbo].[usp_AddUserData]
END
GO
CREATE PROCEDURE dbo.usp_AddUserData (
    @NOMBRE VARCHAR(200),
    @CONTRASENA VARCHAR(200),
    @EMAIL VARCHAR(200),
    @TIPOMEMBRESIA VARCHAR(200),
    @FECHAINICIO VARCHAR(200),
    @FECHAFINALIZACION VARCHAR(200),
    @UNIDADTEMP VARCHAR(200),
	@FORMATOHORAS VARCHAR(200),
	@FORMATOFECHAS VARCHAR(200),
	@PUNTOSTOTALES INT,
	@PUNTOSDIARIOS INT,
	@FECHAACTUALIZACION VARCHAR(200),
	@IDTARJETA INT,
    @ID INT OUTPUT
) AS
BEGIN
    INSERT INTO USUARIO (NOMBRE, CONTRASENA, EMAIL, TIPOMEMBRESIA, FECHAINICIO, FECHAFINALIZACION, UNIDADTEMP, FORMATOHORAS, FORMATOFECHAS, PUNTOSTOTALES, PUNTOSDIARIOS, FECHAACTUALIZACION, IDTARJETA)
    VALUES (@NOMBRE, @CONTRASENA, @EMAIL, @TIPOMEMBRESIA, @FECHAINICIO, @FECHAFINALIZACION, @UNIDADTEMP, @FORMATOHORAS, @FORMATOFECHAS, @PUNTOSTOTALES, @PUNTOSDIARIOS, @FECHAACTUALIZACION, @IDTARJETA)

    SET @ID = SCOPE_IDENTITY()
END
SELECT * FROM USUARIO
SELECT * FROM PREGUNTASPORDIA
SELECT * FROM TARJETAS
GO

IF EXISTS ( SELECT * 
            FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[usp_UpdateUserData]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE [dbo].[usp_UpdateUserData]
END
GO
CREATE PROCEDURE dbo.usp_UpdateUserData(
	@ID   INT,
    @NOMBRE VARCHAR(200),
    @CONTRASENA VARCHAR(200),
    @EMAIL VARCHAR(200),
    @TIPOMEMBRESIA VARCHAR(200),
    @FECHAINICIO VARCHAR(200),
    @FECHAFINALIZACION VARCHAR(200),
    @UNIDADTEMP VARCHAR(200),
	@FORMATOHORAS VARCHAR(200),
	@FORMATOFECHAS VARCHAR(200),
	@PUNTOSTOTALES INT,
	@PUNTOSDIARIOS INT,
	@FECHAACTUALIZACION VARCHAR(200),
	@IDTARJETA INT
) AS 
BEGIN
	UPDATE USUARIO 
	SET 
		NOMBRE = @NOMBRE, 
		CONTRASENA = @CONTRASENA, 
		EMAIL = @EMAIL, 
		TIPOMEMBRESIA = @TIPOMEMBRESIA, 
		FECHAINICIO = @FECHAINICIO, 
		FECHAFINALIZACION = @FECHAFINALIZACION, 
		UNIDADTEMP = @UNIDADTEMP, 
		FORMATOHORAS = @FORMATOHORAS, 
		FORMATOFECHAS = @FORMATOFECHAS,
		PUNTOSTOTALES = @PUNTOSTOTALES, 
		PUNTOSDIARIOS = @PUNTOSDIARIOS, 
		FECHAACTUALIZACION = @FECHAACTUALIZACION, 
		IDTARJETA = @IDTARJETA
	WHERE ID = @ID
END
GO


---
IF EXISTS ( SELECT * 
            FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[usp_DeleteUserData]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE [dbo].[usp_DeleteUserData]
END
GO
CREATE PROCEDURE dbo.usp_DeleteUserData(
    @ID         INT
) AS 
BEGIN
	DELETE FROM USUARIO 
	WHERE ID=@ID
END
GO



--- preguntospordia

IF OBJECT_ID('dbo.PREGUNTASPORDIA', 'U') IS NOT NULL 
  DROP TABLE dbo.PREGUNTASPORDIA 
GO
CREATE TABLE PREGUNTASPORDIA
( 
    IDUSUARIO INT NOT NULL,
	P1 INT NOT NULL,
	P2 INT NOT NULL,
	P3 INT NOT NULL,
	P4 INT NOT NULL,
	P5 INT NOT NULL
)

IF EXISTS (
    SELECT *
    FROM sysobjects
    WHERE id = object_id(N'[dbo].[usp_AddPreguntasporDia]')
        AND OBJECTPROPERTY(id, N'IsProcedure') = 1
)
BEGIN
    DROP PROCEDURE [dbo].[usp_AddPreguntasporDia]
END
GO
CREATE PROCEDURE dbo.usp_AddPreguntasporDia (
    @IDUSUARIO INT,
	@P1 INT,
	@P2 INT,
	@P3 INT,
	@P4 INT,
	@P5 INT
) AS
BEGIN
    INSERT INTO PREGUNTASPORDIA (IDUSUARIO, P1, P2, P3, P4, P5)
    VALUES (@IDUSUARIO, @P1, @P2, @P3, @P4, @P5)
END
GO

IF EXISTS ( SELECT * 
            FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[usp_UpdatePreguntasporDia]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE [dbo].[usp_UpdatePreguntasporDia]
END
GO
CREATE PROCEDURE dbo.usp_UpdatePreguntasporDia(
	@IDUSUARIO INT,
	@P1 INT,
	@P2 INT,
	@P3 INT,
	@P4 INT,
	@P5 INT
) AS 
BEGIN
	UPDATE PREGUNTASPORDIA 
	SET 
		P1 = @P1,
		P2 = @P2,
		P3 = @P3,
		P4 = @P4,
		P5 = @P5
	WHERE IDUSUARIO = @IDUSUARIO
END
GO

IF EXISTS ( SELECT * 
            FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[usp_QueryPreguntasporDia]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
    DROP PROCEDURE [dbo].[usp_QueryPreguntasporDia]
END
GO
CREATE PROCEDURE dbo.usp_QueryPreguntasporDia AS 
BEGIN
	SELECT * FROM PREGUNTASPORDIA 
END

INSERT INTO PREGUNTASPORDIA(IDUSUARIO, P1, P2, P3, P4, P5) 
VALUES 
    (1,0,0, 0, 0, 0);
SELECT * FROM PREGUNTASPORDIA
SELECT * FROM TARJETAS
SELECT * FROM USUARIO
SELECT * FROM PREGUNTAS